export type Product = {
  id: string;
  name: string;
  category: string;
  description: string;
  price: number;
  originalPrice: number;
  type: "item" | "vendor" | "bundle";
  badge?: "BEST DEAL" | "Sale" | "New";
  featured?: boolean;
  image?: string; // Placeholder for now
};

export const products: Product[] = [
  {
    id: "all-supplier-bundle",
    name: "ALL SUPPLIER BUNDLE",
    category: "Bundle",
    description: "Get access to every single supplier we offer. The ultimate reselling toolkit.",
    price: 29.99,
    originalPrice: 50.00,
    type: "bundle",
    badge: "BEST DEAL",
    featured: true,
  },
  {
    id: "labubuu-vendor",
    name: "LABUBUU VENDOR",
    category: "Vendor List",
    description: "Direct source for Labubuu items.",
    price: 19.99,
    originalPrice: 30.00,
    type: "vendor",
    badge: "Sale",
    featured: true,
  },
  {
    id: "shoes-bundle",
    name: "SHOES BUNDLE",
    category: "Bundle",
    description: "Top tier sneaker suppliers including rare finds.",
    price: 24.99,
    originalPrice: 40.00,
    type: "bundle",
    badge: "Sale",
    featured: true,
  },
  {
    id: "hoodies-vendor",
    name: "HOODIES VENDOR",
    category: "Vendor List",
    description: "High quality streetwear hoodie manufacturers.",
    price: 19.99,
    originalPrice: 30.00,
    type: "vendor",
    featured: true,
  },
  {
    id: "sweatpants-vendor",
    name: "SWEATPANTS VENDOR",
    category: "Vendor List",
    description: "Premium sweatpants and joggers suppliers.",
    price: 19.99,
    originalPrice: 30.00,
    type: "vendor",
    featured: true,
  },
  {
    id: "cologne-vendor",
    name: "COLOGNE VENDOR",
    category: "Vendor List",
    description: "Luxury fragrance suppliers.",
    price: 19.99,
    originalPrice: 35.00,
    type: "vendor",
    featured: true,
  },
  {
    id: "peps-vendor",
    name: "PEPS VENDOR",
    category: "Vendor List",
    description: "Exclusive supplier list.",
    price: 19.99,
    originalPrice: 30.00,
    type: "vendor",
  },
  {
    id: "bags-vendor-bundle",
    name: "BAGS VENDOR BUNDLE",
    category: "Bundle",
    description: "Luxury handbags and travel gear suppliers.",
    price: 24.99,
    originalPrice: 45.00,
    type: "bundle",
    badge: "Sale",
    featured: true,
  },
  {
    id: "bracelets-vendor",
    name: "BRACELETS VENDOR",
    category: "Vendor List",
    description: "Jewelry and bracelet manufacturers.",
    price: 14.99,
    originalPrice: 25.00,
    type: "vendor",
  },
  {
    id: "moissanite-vendor",
    name: "MOISSANITE VENDOR",
    category: "Vendor List",
    description: "Certified Moissanite jewelry suppliers.",
    price: 19.99,
    originalPrice: 30.00,
    type: "vendor",
    badge: "Sale",
    featured: true,
  },
  {
    id: "phone-vendor",
    name: "PHONE VENDOR",
    category: "Vendor List",
    description: "Refurbished and new smartphone distributors.",
    price: 24.99,
    originalPrice: 40.00,
    type: "vendor",
    badge: "Sale",
    featured: true,
  },
  {
    id: "watch-vendor",
    name: "WATCH VENDOR",
    category: "Vendor List",
    description: "Luxury and smart watch suppliers.",
    price: 19.99,
    originalPrice: 35.00,
    type: "vendor",
  },
  {
    id: "console-vendor",
    name: "CONSOLE VENDOR",
    category: "Vendor List",
    description: "Gaming consoles and accessories.",
    price: 24.99,
    originalPrice: 40.00,
    type: "vendor",
  },
  {
    id: "camera-vendor",
    name: "CAMERA VENDOR",
    category: "Vendor List",
    description: "Digital cameras and photography equipment.",
    price: 19.99,
    originalPrice: 35.00,
    type: "vendor",
  },
  {
    id: "all-electronics-vendor-bundle",
    name: "ALL ELECTRONICS VENDOR BUNDLE",
    category: "Bundle",
    description: "Complete electronics supplier list.",
    price: 34.99,
    originalPrice: 60.00,
    type: "bundle",
    badge: "Sale",
    featured: true,
  },
  {
    id: "pod-vendor",
    name: "POD VENDOR",
    category: "Vendor List",
    description: "Wireless earbud suppliers.",
    price: 14.99,
    originalPrice: 25.00,
    type: "vendor",
  },
  {
    id: "shirt-shorts-vendor-bundle",
    name: "SHIRT/SHORTS VENDOR BUNDLE",
    category: "Bundle",
    description: "Summer apparel suppliers.",
    price: 24.99,
    originalPrice: 40.00,
    type: "bundle",
  },
  {
    id: "jerseys-supplier",
    name: "JERSEYS SUPPLIER",
    category: "Vendor List",
    description: "Sports jersey manufacturers.",
    price: 19.99,
    originalPrice: 30.00,
    type: "vendor",
  },
  {
    id: "casino-vendor",
    name: "CASINO VENDOR",
    category: "Vendor List",
    description: "Casino equipment and supplies.",
    price: 19.99,
    originalPrice: 30.00,
    type: "vendor",
  },
  {
    id: "all-inflatable-decorations-vendor",
    name: "ALL INFLATABLE DECORATIONS VENDOR",
    category: "Vendor List",
    description: "Party and holiday inflatable decorations.",
    price: 14.99,
    originalPrice: 25.00,
    type: "vendor",
  },
  {
    id: "car-parts-vendor",
    name: "CAR PARTS VENDOR",
    category: "Vendor List",
    description: "Aftermarket car parts and accessories.",
    price: 29.99,
    originalPrice: 50.00,
    type: "vendor",
  },
  {
    id: "shipping-services-vendor",
    name: "SHIPPING SERVICES VENDOR",
    category: "Vendor List",
    description: "Discounted shipping service providers.",
    price: 19.99,
    originalPrice: 30.00,
    type: "vendor",
  },
  {
    id: "furniture-vendor",
    name: "FURNITURE VENDOR",
    category: "Vendor List",
    description: "Modern furniture dropshippers.",
    price: 29.99,
    originalPrice: 50.00,
    type: "vendor",
  }
];

